-- MySQL Script generated by MySQL Workbench
-- Wed Jan 21 16:14:35 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Role` ;

CREATE TABLE IF NOT EXISTS `Role` (
  `roleID` INT NOT NULL AUTO_INCREMENT,
  `role_name` ENUM('TEACHING', 'ADMINISTRATIVE') NULL,
  PRIMARY KEY (`roleID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Employment_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Employment_type` ;

CREATE TABLE IF NOT EXISTS `Employment_type` (
  `typeID` INT NOT NULL AUTO_INCREMENT,
  `type_name` ENUM('PERMANENT', 'CONTRACTOR') NULL,
  PRIMARY KEY (`typeID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Department` ;

CREATE TABLE IF NOT EXISTS `Department` (
  `departmentID` INT NOT NULL AUTO_INCREMENT,
  `department_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`departmentID`),
  UNIQUE INDEX `department_name_UNIQUE` (`department_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Employee` ;

CREATE TABLE IF NOT EXISTS `Employee` (
  `idEmployee` INT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(255) NULL,
  `iban` VARCHAR(45) NULL,
  `phone_number` VARCHAR(12) NULL,
  `is_Married` TINYINT NULL,
  `bank` VARCHAR(45) NULL,
  `employment_starting_date` DATE NULL,
  `name` VARCHAR(45) NULL,
  `Role_roleID` INT NOT NULL,
  `Employment_type_typeID` INT NOT NULL,
  `Department_departmentID` INT NOT NULL,
  `Is_Active` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`idEmployee`),
  INDEX `fk_Employee_Role1_idx` (`Role_roleID` ASC) VISIBLE,
  INDEX `fk_Employee_Employment_type1_idx` (`Employment_type_typeID` ASC) VISIBLE,
  INDEX `fk_Employee_Department1_idx` (`Department_departmentID` ASC) VISIBLE,
  CONSTRAINT `fk_Employee_Role1`
    FOREIGN KEY (`Role_roleID`)
    REFERENCES `Role` (`roleID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Employee_Employment_type1`
    FOREIGN KEY (`Employment_type_typeID`)
    REFERENCES `Employment_type` (`typeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Employee_Department1`
    FOREIGN KEY (`Department_departmentID`)
    REFERENCES `Department` (`departmentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Child`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Child` ;

CREATE TABLE IF NOT EXISTS `Child` (
  `age` INT NULL,
  `name` VARCHAR(45) NOT NULL,
  `Employee_idEmployee` INT NOT NULL,
  PRIMARY KEY (`Employee_idEmployee`, `name`),
  CONSTRAINT `fk_Child_Employee1`
    FOREIGN KEY (`Employee_idEmployee`)
    REFERENCES `Employee` (`idEmployee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Contract`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Contract` ;

CREATE TABLE IF NOT EXISTS `Contract` (
  `idContract` INT NOT NULL AUTO_INCREMENT,
  `start_Date` DATE NOT NULL,
  `end_Date` DATE NOT NULL,
  `salary` DECIMAL(10,2) NOT NULL,
  `Employee_idEmployee` INT NOT NULL,
  PRIMARY KEY (`idContract`),
  INDEX `fk_Contract_Employee1_idx` (`Employee_idEmployee` ASC) VISIBLE,
  CONSTRAINT `fk_Contract_Employee1`
    FOREIGN KEY (`Employee_idEmployee`)
    REFERENCES `Employee` (`idEmployee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Payment` ;

CREATE TABLE IF NOT EXISTS `Payment` (
  `idPayment` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NULL,
  `amount` DECIMAL(10,2) NOT NULL,
  `Employee_idEmployee` INT NOT NULL,
  PRIMARY KEY (`idPayment`),
  INDEX `fk_Payment_Employee1_idx` (`Employee_idEmployee` ASC) VISIBLE,
  CONSTRAINT `fk_Payment_Employee1`
    FOREIGN KEY (`Employee_idEmployee`)
    REFERENCES `Employee` (`idEmployee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Salary_rates`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Salary_rates` ;

CREATE TABLE IF NOT EXISTS `Salary_rates` (
  `base_salary` DECIMAL(10,2) NULL,
  `Role_roleID` INT NOT NULL,
  PRIMARY KEY (`Role_roleID`),  
  INDEX `fk_Salary_rates_Role1_idx` (`Role_roleID` ASC) VISIBLE,
  CONSTRAINT `fk_Salary_rates_Role1`
    FOREIGN KEY (`Role_roleID`)
    REFERENCES `Role` (`roleID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Allowences`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Allowences` ;

CREATE TABLE IF NOT EXISTS `Allowences` (
  `typeID` INT NOT NULL,
  `research_allowence` DECIMAL(10,2) NULL,
  `library_allowence` DECIMAL(10,2) NULL,
  PRIMARY KEY (`typeID`),
  CONSTRAINT `fk_Allowences_Employment_type1`
    FOREIGN KEY (`typeID`)
    REFERENCES `Employment_type` (`typeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- -----------------------------
-- ------ Views (Bonus) --------
-- -----------------------------

-- View 1: Full details (Joins Employee with Role, Dept, Type, Allowance, Contract)
CREATE OR REPLACE VIEW View_Full_Employee_Details AS
SELECT 
    e.idEmployee, 
    e.name, 
    r.role_name, 
    d.department_name,
    et.type_name as employment_type,
    c.salary as contract_salary,
    a.research_allowence,
    a.library_allowence
FROM Employee e
JOIN Role r ON e.Role_roleID = r.roleID
JOIN Department d ON e.Department_departmentID = d.departmentID
JOIN Employment_type et ON e.Employment_type_typeID = et.typeID
LEFT JOIN Contract c ON e.idEmployee = c.Employee_idEmployee
LEFT JOIN Allowences a ON e.idEmployee = a.Employee_idEmployee;

-- View 2: Payroll Stats per Department
CREATE OR REPLACE VIEW View_Department_Payroll AS
SELECT 
    d.department_name,
    SUM(p.amount) AS total_cost,
    COUNT(p.idPayment) AS employees_paid
FROM Payment p
JOIN Employee e ON p.Employee_idEmployee = e.idEmployee
JOIN Department d ON e.Department_departmentID = d.departmentID
GROUP BY d.department_name;

-- View 3: Expiring Contracts (For Contractors)
CREATE OR REPLACE VIEW View_Expiring_Contracts AS
SELECT 
    e.idEmployee, 
    e.name, 
    d.department_name, 
    c.end_Date, 
    c.salary
FROM Employee e
JOIN Department d ON e.Department_departmentID = d.departmentID
JOIN Contract c ON e.idEmployee = c.Employee_idEmployee
WHERE c.end_Date > CURDATE()
ORDER BY c.end_Date ASC;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
