-- MySQL Script generated by MySQL Workbench
-- Mon Jan 12 17:56:57 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS `university_payroll`;
USE `university_payroll`;

-- -----------------------------------------------------
-- 1. Table `Department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Department` ;

CREATE TABLE IF NOT EXISTS `Department` (
  `department_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`department_name`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- 2. Table `SalaryRates` (ΠΡΕΠΕΙ ΝΑ ΔΗΜΙΟΥΡΓΗΘΕΙ ΠΡΙΝ ΤΟ EMPLOYEE)
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SalaryRates`;

CREATE TABLE IF NOT EXISTS `SalaryRates` (
  `role_name` VARCHAR(45) NOT NULL,
  `base_salary` DECIMAL(10,2) NOT NULL, 
  PRIMARY KEY (`role_name`)             
)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- 3. Table `Employee` (Με 2 Foreign Keys τώρα)
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Employee` ;

CREATE TABLE IF NOT EXISTS `Employee` (
  `idEmployee` INT NOT NULL,
  `address` VARCHAR(255) NULL,
  `iban` VARCHAR(45) NULL,
  `phone_number` VARCHAR(45) NULL,
  `is_Married` TINYINT NULL,
  `bank` VARCHAR(45) NULL,
  `employment_starting_date` DATE NULL,
  `name` VARCHAR(45) NULL,
  `Department_Department_name` VARCHAR(45) NOT NULL,
  `Is_Active` TINYINT NOT NULL DEFAULT 1,
  `Role` VARCHAR(45) NOT NULL, -- Αφαιρέσαμε το default 'UNKNOWN' για να αναγκάσουμε σωστή εγγραφή
  PRIMARY KEY (`idEmployee`),
  
  -- Foreign Key 1: Department
  INDEX `fk_Employee_Department_idx` (`Department_Department_name` ASC) VISIBLE,
  CONSTRAINT `fk_Employee_Department`
    FOREIGN KEY (`Department_Department_name`)
    REFERENCES `Department` (`department_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,

  -- Foreign Key 2: Role (Σύνδεση με SalaryRates)
  INDEX `fk_Employee_Role_idx` (`Role` ASC) VISIBLE,
  CONSTRAINT `fk_Employee_Role`
    FOREIGN KEY (`Role`)
    REFERENCES `SalaryRates` (`role_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Οι υπόλοιποι πίνακες (παραμένουν ίδιοι)
-- -----------------------------------------------------

-- Table `Child`
DROP TABLE IF EXISTS `Child` ;
CREATE TABLE IF NOT EXISTS `Child` (
  `age` INT NULL,
  `name` VARCHAR(45) NOT NULL,
  `Employee_idEmployee` INT NOT NULL,
  PRIMARY KEY (`Employee_idEmployee`, `name`),
  CONSTRAINT `fk_Child_Employee1`
    FOREIGN KEY (`Employee_idEmployee`)
    REFERENCES `Employee` (`idEmployee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- Table `Permanent`
DROP TABLE IF EXISTS `Permanent` ;
CREATE TABLE IF NOT EXISTS `Permanent` (
  `Years_of_employment` INT NULL,
  `Employee_idEmployee` INT NOT NULL,
  PRIMARY KEY (`Employee_idEmployee`),
  CONSTRAINT `fk_Permenant_Employee1`
    FOREIGN KEY (`Employee_idEmployee`)
    REFERENCES `Employee` (`idEmployee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- Table `Contractor`
DROP TABLE IF EXISTS `Contractor` ;
CREATE TABLE IF NOT EXISTS `Contractor` (
  `Employee_idEmployee` INT NOT NULL,
  PRIMARY KEY (`Employee_idEmployee`),
  CONSTRAINT `fk_Contractor_Employee1`
    FOREIGN KEY (`Employee_idEmployee`)
    REFERENCES `Employee` (`idEmployee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- Table `Contract`
DROP TABLE IF EXISTS `Contract` ;
CREATE TABLE IF NOT EXISTS `Contract` (
  `idContract` INT NOT NULL,
  `start_Date` DATE NULL,
  `end_Date` DATE NULL,
  `salary` DECIMAL(10,2) NULL,
  `Contractor_Employee_idEmployee` INT NOT NULL,
  PRIMARY KEY (`idContract`),
  INDEX `fk_Contract_Contractor1_idx` (`Contractor_Employee_idEmployee` ASC) VISIBLE,
  CONSTRAINT `fk_Contract_Contractor1`
    FOREIGN KEY (`Contractor_Employee_idEmployee`)
    REFERENCES `Contractor` (`Employee_idEmployee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- Table `Permanent Teaching Employee`
DROP TABLE IF EXISTS `Permanent_Teaching_Employee` ;
CREATE TABLE IF NOT EXISTS `Permanent Teaching Employee` (
  `research_allowence` DECIMAL(10,2) NULL,
  `Permenant_Employee_idEmployee` INT NOT NULL,
  PRIMARY KEY (`Permenant_Employee_idEmployee`),
  CONSTRAINT `fk_Permenant Teaching Employee_Permenant1`
    FOREIGN KEY (`Permenant_Employee_idEmployee`)
    REFERENCES `Permanent` (`Employee_idEmployee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- Table `Permanent Administrative Employee`
DROP TABLE IF EXISTS `Permanent_Administrative_Employee` ;
CREATE TABLE IF NOT EXISTS `Permanent Administrative Employee` (
  `Permenant_Employee_idEmployee` INT NOT NULL,
  PRIMARY KEY (`Permenant_Employee_idEmployee`),
  CONSTRAINT `fk_Permenant Administrative Employee_Permenant1`
    FOREIGN KEY (`Permenant_Employee_idEmployee`)
    REFERENCES `Permanent` (`Employee_idEmployee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- Table `Contractor Teaching Employee`
DROP TABLE IF EXISTS `Contractor_Teaching_Employee` ;
CREATE TABLE IF NOT EXISTS `Contractor Teaching Employee` (
  `library_allowence` DECIMAL(10,2) NULL,
  `Contractor_Employee_idEmployee` INT NOT NULL,
  PRIMARY KEY (`Contractor_Employee_idEmployee`),
  CONSTRAINT `fk_Contractor Teaching Employee_Contractor1`
    FOREIGN KEY (`Contractor_Employee_idEmployee`)
    REFERENCES `Contractor` (`Employee_idEmployee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- Table `Contractor Administrative Employee`
DROP TABLE IF EXISTS `Contractor_Administrative_Employee` ;
CREATE TABLE IF NOT EXISTS `Contractor Administrative Employee` (
  `Contractor_Employee_idEmployee` INT NOT NULL,
  PRIMARY KEY (`Contractor_Employee_idEmployee`),
  CONSTRAINT `fk_Contractor Administrative Employee_Contractor1`
    FOREIGN KEY (`Contractor_Employee_idEmployee`)
    REFERENCES `Contractor` (`Employee_idEmployee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- Table `Payment`
DROP TABLE IF EXISTS `Payment` ;
CREATE TABLE IF NOT EXISTS `Payment` (
  `idPayment` INT NOT NULL,
  `date` DATE NULL,
  `amount` DECIMAL(10,2) NULL,
  `Employee_idEmployee` INT NOT NULL,
  PRIMARY KEY (`idPayment`),
  INDEX `fk_Payment_Employee1_idx` (`Employee_idEmployee` ASC) VISIBLE,
  CONSTRAINT `fk_Payment_Employee1`
    FOREIGN KEY (`Employee_idEmployee`)
    REFERENCES `Employee` (`idEmployee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------
-- ------ Views (Bonus) --------
-- -----------------------------
CREATE OR REPLACE VIEW View_Full_Employee_Details AS
SELECT 
    e.idEmployee, e.name, e.Role, e.Department_Department_name,
    p.Years_of_employment, 
    c.salary as contractor_salary
FROM Employee e
LEFT JOIN Permanent p ON e.idEmployee = p.Employee_idEmployee
LEFT JOIN Contractor cnt ON e.idEmployee = cnt.Employee_idEmployee
LEFT JOIN Contract c ON cnt.Employee_idEmployee = c.Contractor_Employee_idEmployee;

CREATE OR REPLACE VIEW View_Department_Payroll AS
    SELECT 
        e.Department_Department_name,
        SUM(p.amount) AS total_cost,
        COUNT(p.idPayment) AS employees_paid
    FROM
        Payment p
            JOIN
        Employee e ON p.Employee_idEmployee = e.idEmployee
    GROUP BY e.Department_Department_name;

CREATE OR REPLACE VIEW View_Expiring_Contracts AS
SELECT 
    e.idEmployee, e.name, e.Department_Department_name, 
    c.end_Date, c.salary
FROM Employee e
JOIN Contractor cnt ON e.idEmployee = cnt.Employee_idEmployee
JOIN Contract c ON cnt.Employee_idEmployee = c.Contractor_Employee_idEmployee
WHERE c.end_Date > CURDATE()
ORDER BY c.end_Date ASC;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
